"""Base plugin interface for edge-case devices."""
from __future__ import annotations
import re
from abc import ABC, abstractmethod
from typing import TYPE_CHECKING

from ..core.types import DeviceInfo, PluginManifest, DataPacket
from ..core.connector import BaseConnector

if TYPE_CHECKING:
    from ..adapters.base import BaseAdapter


class BasePlugin(ABC):
    """
    Base class for edge-case device plugins.
    
    Extend this to handle proprietary protocols discovered via sniffer.
    """
    
    def __init__(self):
        self._manifest = self._define_manifest()
    
    @property
    def manifest(self) -> PluginManifest:
        return self._manifest
    
    @abstractmethod
    def _define_manifest(self) -> PluginManifest:
        """Define plugin metadata. Override in subclass."""
        ...
    
    def matches(self, device: DeviceInfo) -> bool:
        """
        Check if this plugin handles the given device.
        
        Default: match by name patterns in manifest.
        Override for custom matching logic.
        """
        for pattern in self._manifest.device_patterns:
            if re.search(pattern, device.name, re.IGNORECASE):
                return True
            if device.manufacturer and re.search(pattern, device.manufacturer, re.IGNORECASE):
                return True
        return False
    
    @abstractmethod
    async def create_connector(
        self, device: DeviceInfo, adapter: BaseAdapter
    ) -> BaseConnector:
        """
        Create a custom connector for this device.
        
        Use the adapter's underlying connection, but wrap with
        proprietary protocol handling.
        """
        ...
    
    @abstractmethod
    def parse_data(self, packet: DataPacket) -> dict:
        """
        Parse proprietary data format.
        
        Called by normalizer to decode device-specific payloads.
        """
        ...


# Example plugin template (generated by sniffer)
PLUGIN_TEMPLATE = '''
"""Plugin for {device_name}."""
from eve_peripheral_bridge.plugins.base import BasePlugin
from eve_peripheral_bridge.core.types import DeviceInfo, PluginManifest, DataPacket
from eve_peripheral_bridge.core.connector import BaseConnector


class {class_name}Plugin(BasePlugin):
    """Handler for {device_name} ({vendor})."""
    
    def _define_manifest(self) -> PluginManifest:
        return PluginManifest(
            id="{plugin_id}",
            name="{device_name} Plugin",
            vendor="{vendor}",
            device_patterns={patterns},
        )
    
    async def create_connector(self, device: DeviceInfo, adapter) -> BaseConnector:
        # Get base connector
        connector = await adapter.create_connector(device)
        await connector.connect()
        
        # TODO: Implement proprietary handshake
        # Based on sniffer analysis:
        # {sniffer_notes}
        
        return connector
    
    def parse_data(self, packet: DataPacket) -> dict:
        raw = packet.raw
        
        # TODO: Implement payload parsing
        # Field map from sniffer:
        # {field_map}
        
        return {{
            "raw_hex": raw.hex(),
            # Add parsed fields here
        }}
'''
